//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentTypeCharacteristic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComponentTypeCharacteristic()
        {
            this.ComponentCharacteristic = new HashSet<ComponentCharacteristic>();
        }
    
        public int Id { get; set; }
        public int ComponentTypeId { get; set; }
        public int CharacteristicId { get; set; }
    
        public virtual Characteristiс Characteristiс { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentCharacteristic> ComponentCharacteristic { get; set; }
        public virtual ComponentType ComponentType { get; set; }
    }
}
