//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentLocation
    {
        public int Id { get; set; }
        public int LocationId { get; set; }
        public int EquipmentId { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsActual { get; set; }
    
        public virtual string IsActualString => IsActual ? "Текущее" : "Не актуально";
        public virtual Equipment Equipment { get; set; }
        public virtual Location Location { get; set; }
    }
}
