//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.EquipmentComponent = new HashSet<EquipmentComponent>();
            this.EquipmentLocation = new HashSet<EquipmentLocation>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime InventoryDate { get; set; }
        public string InventoryNumber { get; set; }
        public string SerialNumber { get; set; }
        public int StateId { get; set; }
        public int EquipmentTypeId { get; set; }
        public string Note { get; set; }
    
        public virtual EquipmentType EquipmentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentComponent> EquipmentComponent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentLocation> EquipmentLocation { get; set; }
        public virtual State State { get; set; }
    }
}
